input_data_path: "data/raw/heart.csv"
input_data_for_validation: "data/input/data_to_predict.csv"
output_model_path: "models/logistic_regression.pkl"
output_data_preprocessor_path: "models/data_preprocessor_lr.pkl"
predicts_path: "data/pred/predicts.csv"
logger_config: "configs/config_log.yml"
model_type: "Logistic Regression"
split_params:
  validation_size: 0.2
  random_state: 42
feature_params:
  numerical_features:   ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
  categorical_features: ['sex', 'cp', 'fbs', 'restecg', 'exang', 'slope', 'ca', 'thal']
  target: 'target'
classifier_params:
  C: 1.0
  penalty: "l2"
  fit_intercept: True
  random_state: 42
